ItemNames_33 = {
    ["245889"] = {en = "Large Charm of Dexterity", zh = "敏捷之大型神符"},
    ["245890"] = {en = "Large Charm of Strength", zh = "力量之大型神符"},
    ["245891"] = {en = "Small Charm of Inertia", zh = "惯性之小型神符"},
    ["245892"] = {en = "Small Charm of Life", zh = "生命之小型神符"},
    ["245893"] = {en = "Small Charm of Alacrity", zh = "迅速之小型神符"},
    ["245894"] = {en = "Small Charm of Proficiency", zh = "精通之小型神符"},
    ["245895"] = {en = "Small Charm of Savagery", zh = "野蛮之小型神符"},
    ["245896"] = {en = "Small Charm of Adaptability", zh = "适应之小型神符"},
    ["245899"] = {en = "Bat's Grand Charm", zh = "恶蝠的巨型神符"},
    ["245924"] = {en = "Mongoose's Grand Charm", zh = "猫鼬的巨型神符"},
    ["245936"] = {en = "Unarmored Deathtusk Felboar", zh = "轻装死牙魔能野猪"},
    ["245942"] = {en = "Sea-Blessed Shrine", zh = "海潮祝福神龛"},
    ["245946"] = {en = "Brewer's Balloon", zh = "酿酒师的气球"},
    ["245947"] = {en = "Barrel Helm", zh = "酒桶护盔"},
    ["245948"] = {en = "Bronzebeard's Portable Forge", zh = "铜须的随身熔炉"},
    ["245949"] = {en = "The Speaker's Portable Forge", zh = "代言人的随身熔炉"},
    ["245950"] = {en = "Dark Iron Portable Forge", zh = "黑铁的随身熔炉"},
    ["245951"] = {en = "Wildhammer's Portable Forge", zh = "蛮锤的随身熔炉"},
    ["245952"] = {en = "Bronzebeard's Ceremonial Gavel", zh = "铜须的仪式轻锤"},
    ["245953"] = {en = "The Speaker's Ceremonial Mallet", zh = "代言人的仪式槌杖"},
    ["245954"] = {en = "Wildhammer's Ceremonial Mace", zh = "蛮锤的仪式之锤"},
    ["245955"] = {en = "Dark Iron's Ceremonial Mace", zh = "黑铁的仪式之锤"},
    ["245956"] = {en = "Bronzebeard's Crystal Ward", zh = "铜须的防御水晶"},
    ["245957"] = {en = "The Speaker's Crystal Ward", zh = "代言人的防御水晶"},
    ["245958"] = {en = "Wildhammer's Crystal Ward", zh = "蛮锤的防御水晶"},
    ["245959"] = {en = "Dark Iron's Crystal Ward", zh = "黑铁的防御水晶"},
    ["245964"] = {en = "Durable Information Securing Container", zh = "牢固信息保全容器"},
    ["245965"] = {en = "Durable Information Securing Container", zh = "牢固信息保全容器"},
    ["245966"] = {en = "Durable Information Securing Container", zh = "牢固信息保全容器"},
    ["245967"] = {en = "Shawl of the Trust", zh = "托拉斯披巾"},
    ["245968"] = {en = "Tabard of the Trust", zh = "托拉斯战袍"},
    ["245969"] = {en = "Mantle of the Trust", zh = "托拉斯披肩"},
    ["245970"] = {en = "P.O.S.T. Master's Express Hearthstone", zh = "P.O.S.T.总管的特快炉石"},
    ["245971"] = {en = "Consortium Brute's Clasp", zh = "星界财团蛮兵的腕甲"},
    ["245972"] = {en = "Consortium Skirmisher's Armbands", zh = "星界财团散兵的腕带"},
    ["245973"] = {en = "Consortium Scout's Armlets", zh = "星界财团斥候的护臂"},
    ["245974"] = {en = "Consortium Magi's Cuffs", zh = "星界财团法师的腕扣"},
    ["245975"] = {en = "Consortium Brute's Chestguard", zh = "星界财团蛮兵的胸铠"},
    ["245976"] = {en = "Consortium Skirmisher's Cuirass", zh = "星界财团散兵的护胸甲"},
    ["245977"] = {en = "Consortium Scout's Jacket", zh = "星界财团斥候的外套"},
    ["245978"] = {en = "Consortium Magi's Robes", zh = "星界财团法师的长袍"},
    ["245979"] = {en = "Arcano-Charged Wrench", zh = "奥术充能扳手"},
    ["245980"] = {en = "Inter-Phase Scoop", zh = "相际挖掘铲"},
    ["245981"] = {en = "K'areshi Multi-Tool", zh = "卡雷什万用工具"},
    ["246015"] = {en = "Classic Midnight Eye Patch", zh = "经典午夜眼罩"},
    ["246016"] = {en = "Classic Snowy Eye Patch", zh = "经典雪白眼罩"},
    ["246041"] = {en = "Brew Keg", zh = "酒桶"},
    ["246042"] = {en = "Pretzel", zh = "脆饼干"},
    ["246044"] = {en = "Bag of Brewfest Ingredients", zh = "一包美酒节食材"},
    ["246052"] = {en = "Barley Soup", zh = "大麦汤"},
    ["246053"] = {en = "Waygate Piece", zh = "界门碎片"},
    ["246063"] = {en = "Void-Polished Warpstalker Stone", zh = "虚空抛光的迁跃兽玉"},
    ["246064"] = {en = "Reshii Magi's Pendant", zh = "雷什法师的挂坠"},
    ["246065"] = {en = "Reshii Magi's Band", zh = "雷什法师的指环"},
    ["246067"] = {en = "Pearlescent Krolusk", zh = "珠光三叶虫"},
    ["246071"] = {en = "Mana-Seamster's Arcane-Needle", zh = "法力裁缝的奥术缝针"},
    ["246086"] = {en = "Fate Weaver", zh = "织命者"},
    ["246114"] = {en = "Catalyst Elixir", zh = "催化药剂"},
    ["246127"] = {en = "Healthy Elixir", zh = "康健药剂"},
    ["246159"] = {en = "Translocated Gorger", zh = "流离的饕餮者"},
    ["246160"] = {en = "Sthaarbs's Last Lunch", zh = "司萨阿布斯最后的午餐"},
    ["246227"] = {en = "Lightning-Blessed Spire", zh = "闪电祝福尖峰"},
    ["246237"] = {en = "OC91 Chariot", zh = "OC91战车"},
    ["246240"] = {en = "Devoured Energy-Pod", zh = "被吞噬的能量舱"},
    ["246242"] = {en = "Blood-Wrapped Treasure Bag", zh = "血迹斑斑的宝物袋"},
    ["246244"] = {en = "Phase-Altered Essence", zh = "相位异变精华"},
    ["246264"] = {en = "Inarius' Charger", zh = "伊纳瑞斯的天使战马"},
    ["246273"] = {en = "Vest of Refracted Shadows", zh = "折射暗影外衣"},
    ["246274"] = {en = "Geezle's Zapstep Boots", zh = "吉泽尔的震步靴"},
    ["246275"] = {en = "Codebreaker's Cunning Handwraps", zh = "解密者的狡诈裹手"},
    ["246276"] = {en = "Sinlight Shoulderpads", zh = "罪孽之光护肩"},
    ["246277"] = {en = "Swampface's Oozewalkers", zh = "沼面的踏泥靴"},
    ["246278"] = {en = "Overpressure Platelegs", zh = "超压力腿甲"},
    ["246279"] = {en = "Fizzlefuse Cuffs", zh = "闪芯袖带"},
    ["246280"] = {en = "Boots of Titanic Deconversion", zh = "泰坦逆转化长靴"},
    ["246281"] = {en = "Ring of the Panoply", zh = "披挂之戒"},
    ["246282"] = {en = "Order Bashers", zh = "指令行使手甲"},
    ["246283"] = {en = "Crown of Absolute Command", zh = "绝对命令头冠"},
    ["246284"] = {en = "Nathrian Reliquary", zh = "纳斯利亚遗物匣"},
    ["246285"] = {en = "Fluxphase Culottes", zh = "通量相位裙裤"},
    ["246286"] = {en = "Spaulders of Unleashed Pride", zh = "无羁傲气肩垫"},
    ["246287"] = {en = "Improvisational Girdle", zh = "即兴束腰"},
    ["246293"] = {en = "Buckler of the Last Stand", zh = "决死轻盾"},
    ["246294"] = {en = "Shattered Buckler of the Last Stand", zh = "碎裂的决死轻盾"},
    ["246295"] = {en = "Tazavesh Lookout's Mace", zh = "塔扎维什哨兵之锤"},
    ["246296"] = {en = "Off-Balance Mace of the Tazavesh Lookout", zh = "失衡的塔扎维什哨兵之锤"},
    ["246297"] = {en = "Desperate Defender's Bladed Staff", zh = "绝望防御者的锋刃杖"},
    ["246298"] = {en = "Cracked Staff of the Desperate Defender", zh = "开裂的绝望防御者之杖"},
    ["246299"] = {en = "Blade of Lost Hope", zh = "失落希望之剑"},
    ["246301"] = {en = "Pitted Blade of Lost Hope", zh = "有凹痕的失落希望之剑"},
    ["246319"] = {en = "Festering Scythe", zh = "脓疮毒镰"},
    ["246337"] = {en = "Rustyroot Fel Snooter", zh = "锈根邪能水豚"},
    ["246339"] = {en = "Duskytooth Fel Snooter", zh = "暮牙邪能水豚"},
    ["246342"] = {en = "Mustyfur Fel Snooter", zh = "霉皮邪能水豚"},
    ["246343"] = {en = "Scruffyhorn Fel Snooter", zh = "乱角邪能水豚"},
    ["246344"] = {en = "Cursed Stone Idol", zh = "被诅咒的岩石雕像"},
    ["246445"] = {en = "Reins of the Royal Voidwing", zh = "皇家虚空之翼的缰绳"},
    ["246446"] = {en = "Mark of the Twilight Oath", zh = "暮光誓言印记"},
    ["246451"] = {en = "Shadefur Brewthief", zh = "影裘小酿盗"},
    ["246492"] = {en = "Soulgorged Augment Rune", zh = "噬魂强化符文"},
    ["246504"] = {en = "Inscrutable Ore", zh = "玄妙矿石"},
    ["246565"] = {en = "Cosmic Hearthstone", zh = "星瀚炉石"},
    ["246570"] = {en = "Rethfuras, Scorched Stave of Cinders", zh = "雷瑟弗拉斯，灰烬炙灼之杖"},
    ["246571"] = {en = "Glazfuris, Spire of the Deep Chill", zh = "格拉兹弗里斯，幽邃冬寒之杖"},
    ["246582"] = {en = "Inscrutable Flora", zh = "玄妙花卉"},
    ["246584"] = {en = "A Steamy Romance Novel: Devouring Love", zh = "一部催人泪下的言情小说：《吞噬的爱》"},
    ["246589"] = {en = "Half-Digested Journal", zh = "消化了一半的日志"},
    ["246592"] = {en = "Shadowguard Credentials", zh = "影卫认证书"},
    ["246593"] = {en = "Shadowguard Credentials", zh = "影卫认证书"},
    ["246694"] = {en = "Zo'ya", zh = "佐·雅"},
    ["246698"] = {en = "Sunwarmed Furline", zh = "暖日绒猫"},
    ["246723"] = {en = "Unfazed Diver", zh = "泰然深潜猫"},
    ["246727"] = {en = "Ethereal Essence Sliver", zh = "虚灵精华残缕"},
    ["246730"] = {en = "Landro's Loot Box", zh = "兰德鲁的豪华礼物盒"},
    ["246732"] = {en = "Void-Forged Overseer", zh = "虚铸监察者"},
    ["246737"] = {en = "K'areshi Voidstone", zh = "卡雷什虚空石"},
    ["246757"] = {en = "Miniature Roulette Wheel", zh = "迷你幸运转盘"},
    ["246758"] = {en = "Miniature Roulette Wheel", zh = "迷你幸运转盘"},
    ["246759"] = {en = "Miniature Roulette Wheel", zh = "迷你幸运转盘"},
    ["246760"] = {en = "Miniature Roulette Wheel", zh = "迷你幸运转盘"},
    ["246761"] = {en = "Miniature Roulette Wheel", zh = "迷你幸运转盘"},
    ["246762"] = {en = "Miniature Roulette Wheel", zh = "迷你幸运转盘"},
    ["246763"] = {en = "Miniature Roulette Wheel", zh = "迷你幸运转盘"},
    ["246764"] = {en = "Miniature Roulette Wheel", zh = "迷你幸运转盘"},
    ["246765"] = {en = "Miniature Roulette Wheel", zh = "迷你幸运转盘"},
    ["246766"] = {en = "Miniature Roulette Wheel", zh = "迷你幸运转盘"},
    ["246767"] = {en = "Miniature Roulette Wheel", zh = "迷你幸运转盘"},
    ["246768"] = {en = "Miniature Roulette Wheel", zh = "迷你幸运转盘"},
    ["246771"] = {en = "Radiant Echo", zh = "光耀回响"},
    ["246772"] = {en = "Radiant Echo", zh = "光耀回响"},
    ["246781"] = {en = "Bronzebeard's Ancient Crusher", zh = "铜须的上古碎击锤"},
    ["246782"] = {en = "The Speaker's Ancient Crusher", zh = "代言人的上古碎击锤"},
    ["246783"] = {en = "Wildhammer's Ancient Crusher", zh = "蛮锤的上古碎击锤"},
    ["246784"] = {en = "Dark Iron's Ancient Crusher", zh = "黑铁的上古碎击锤"},
    ["246785"] = {en = "Coldsnap Felblade", zh = "霜暴邪能利剑"},
    ["246786"] = {en = "Sinister Felblade", zh = "罪恶邪能利剑"},
    ["246787"] = {en = "Hellfire Felblade", zh = "地狱火邪能利剑"},
    ["246788"] = {en = "Netherstorm Felblade", zh = "虚空风暴邪能利剑"},
    ["246790"] = {en = "Coldsnap Feldirk", zh = "霜暴邪能匕首"},
    ["246791"] = {en = "Hellfire Feldirk", zh = "地狱火邪能匕首"},
    ["246792"] = {en = "Netherstorm Feldirk", zh = "虚空风暴邪能匕首"},
    ["246793"] = {en = "Sinister Feldirk", zh = "罪恶邪能匕首"},
    ["246798"] = {en = "Bronzebeard's Mighty Crossbow", zh = "铜须的强击之弩"},
    ["246799"] = {en = "The Speaker's Mighty Crossbow", zh = "代言人的强击之弩"},
    ["246800"] = {en = "Wildhammer's Mighty Crossbow", zh = "蛮锤的强击之弩"},
    ["246801"] = {en = "Dark Iron's Mighty Crossbow", zh = "黑铁的强击之弩"},
    ["246809"] = {en = "Inspired Writer's Quill", zh = "顿悟作家的羽毛笔"},
    ["246811"] = {en = "Technique: Inspired Writer's Quill", zh = "工艺图：顿悟作家的羽毛笔"},
    ["246816"] = {en = "A Steamy Romance Novel: Nightborne of the Living Dead", zh = "一部催人泪下的言情小说：《活死人——夜之子》"},
    ["246817"] = {en = "A Steamy Romance Novel: Of Elven Bondage", zh = "一部催人泪下的言情小说：《精灵的枷锁》"},
    ["246818"] = {en = "A Steamy Romance Novel: Waves of Desire", zh = "一部催人泪下的言情小说：《欲望之潮》"},
    ["246820"] = {en = "A Steamy Romance Novel: Stormy Seas", zh = "一部催人泪下的言情小说：《巨浪之海》"},
    ["246821"] = {en = "A Steamy Romance Novel: The Lusty Draconian Mage", zh = "一部催人泪下的言情小说：《巨龙法师的活力》"},
    ["246822"] = {en = "A Steamy Romance Novel: Devouring Love", zh = "一部催人泪下的言情小说：《吞噬的爱》"},
    ["246823"] = {en = "A Steamy Romance Novel: Got Milk?", zh = "一部催人泪下的言情小说：《牛奶情缘》"},
    ["246824"] = {en = "Shadowguard's Twisted Harvester", zh = "影卫的扭曲收获者"},
    ["246825"] = {en = "Chaotic Nethergate", zh = "混乱虚空之门"},
    ["246837"] = {en = "Mysterious Notebook", zh = "神秘的笔记本"},
    ["246839"] = {en = "Multiversal Energy Dynamics and the Murmuration Paradox", zh = "多维能量动力学与嗫语悖论"},
    ["246840"] = {en = "Ba'key's Aromatic Broker Cookies Recipes", zh = "巴·奇的绝世香气掮灵饼干配方"},
    ["246841"] = {en = "From Vengeance to Void", zh = "从复仇到虚空"},
    ["246842"] = {en = "The Facets of K'aresh", zh = "卡雷什的面向"},
    ["246843"] = {en = "Coins: An Oath We Exchange", zh = "货币：易换的誓言"},
    ["246844"] = {en = "I Have Become Void!", zh = "我，即是虚空！"},
    ["246892"] = {en = "Void's Binding Wraps", zh = "虚空之缚裹手"},
    ["246893"] = {en = "Void's Binding Briefs", zh = "虚空之缚短裤"},
    ["246894"] = {en = "Void's Binding Shade", zh = "虚空之缚遮阳帽"},
    ["246895"] = {en = "Void's Binding Sash", zh = "虚空之缚饰带"},
    ["246896"] = {en = "Void's Binding Anklets", zh = "虚空之缚脚环"},
    ["246897"] = {en = "Void's Binding Halter Top", zh = "虚空之缚吊带上衣"},
    ["246898"] = {en = "Ensemble: Void's Binding Swimwear", zh = "套装：虚空之缚泳装"},
    ["246903"] = {en = "Guise of the Phase Diver", zh = "相位潜者的伪装"},
    ["246904"] = {en = "Unseen Path of the Phase Stalker", zh = "相位追猎者的隐匿之路"},
    ["246905"] = {en = "Overtuned K'areshi Goggles", zh = "过度调整的卡雷什护目镜"},
    ["246907"] = {en = "Broker Supply Crate", zh = "掮灵补给箱"},
    ["246908"] = {en = "K'areshi Supply Crate", zh = "卡雷什补给箱"},
    ["246915"] = {en = "Arsenal: Ethereal Weaponry", zh = "军械：虚灵武器"},
    ["246917"] = {en = "Thunder-ridged Elekk", zh = "雷鸣脊背雷象"},
    ["246919"] = {en = "Cinder-seared Elekk", zh = "余烬焦灼雷象"},
    ["246920"] = {en = "Void-Razed Elekk", zh = "虚空噬灭雷象"},
    ["246921"] = {en = "Legion Forged Elekk", zh = "军团锤炼雷象"},
    ["246939"] = {en = "Essence-Hunter's Eyeglass", zh = "精华猎手的镜片"},
    ["246940"] = {en = "Manaforged Aethercell", zh = "法力熔炉以太电池"},
    ["246941"] = {en = "Symbiotic Ethergauze", zh = "共生以太薄纱"},
    ["246944"] = {en = "Mind-Fracturing Odium", zh = "心智溃解之祸"},
    ["246945"] = {en = "Incorporeal Essence-Gorger", zh = "虚体精华吞噬者"},
    ["246947"] = {en = "Twisted Mana Sprite", zh = "扭曲的法力之魂"},
    ["246949"] = {en = "Felrider's Azure Treads", zh = "邪能骑士的碧蓝之履"},
    ["246950"] = {en = "Felrider's Azure Helm", zh = "邪能骑士的碧蓝之盔"},
    ["246952"] = {en = "Felrider's Azure Shoulderguards", zh = "邪能骑士的碧蓝护肩"},
    ["246956"] = {en = "Felrider's Azure Jacket", zh = "邪能骑士的碧蓝外套"},
    ["246962"] = {en = "Felrider's Azure Belt", zh = "邪能骑士的碧蓝腰带"},
    ["246963"] = {en = "Felrider's Azure Legguards", zh = "邪能骑士的碧蓝护腿"},
    ["246964"] = {en = "Felrider's Azure Gauntlets", zh = "邪能骑士的碧蓝护手"},
    ["246965"] = {en = "Ensemble: Felrider's Azure Attire", zh = "套装：邪能骑士的碧蓝装束"},
    ["246966"] = {en = "Felreaver's Legion Gauntlets", zh = "魔能机甲的军团护手"},
    ["246967"] = {en = "Felreaver's Legion Legguards", zh = "魔能机甲的军团护腿"},
    ["246968"] = {en = "Felreaver's Legion Belt", zh = "魔能机甲的军团腰带"},
    ["246969"] = {en = "Felreaver's Legion Jacket", zh = "魔能机甲的军团外套"},
    ["246970"] = {en = "Felreaver's Legion Shoulderguards", zh = "魔能机甲的军团护肩"},
    ["246971"] = {en = "Felreaver's Legion Helm", zh = "魔能机甲的军团之盔"},
    ["246972"] = {en = "Felreaver's Legion Treads", zh = "魔能机甲的军团之履"},
    ["246973"] = {en = "Ensemble: Felreaver's Legion Attire", zh = "套装：魔能机甲的军团装束"},
    ["246974"] = {en = "Felreaver's Hellfire Gauntlets", zh = "魔能机甲的地狱火护手"},
    ["246975"] = {en = "Felreaver's Hellfire Legguards", zh = "魔能机甲的地狱火护腿"},
    ["246976"] = {en = "Felreaver's Hellfire Belt", zh = "魔能机甲的地狱火腰带"},
    ["246977"] = {en = "Felreaver's Hellfire Jacket", zh = "魔能机甲的地狱火外套"},
    ["246978"] = {en = "Felreaver's Hellfire Shoulderguards", zh = "魔能机甲的地狱火护肩"},
    ["246979"] = {en = "Felreaver's Hellfire Helm", zh = "魔能机甲的地狱火之盔"},
    ["246980"] = {en = "Felreaver's Hellfire Treads", zh = "魔能机甲的地狱火之履"},
    ["246981"] = {en = "Ensemble: Felreaver's Hellfire Attire", zh = "套装：魔能机甲的地狱火装束"},
    ["246982"] = {en = "Felreaver's Arcane Gauntlets", zh = "魔能机甲的奥术护手"},
    ["246983"] = {en = "Felreaver's Arcane Legguards", zh = "魔能机甲的奥术护腿"},
    ["246984"] = {en = "Felreaver's Arcane Belt", zh = "魔能机甲的奥术腰带"},
    ["246985"] = {en = "Felreaver's Arcane Jacket", zh = "魔能机甲的奥术外套"},
    ["246986"] = {en = "Felreaver's Arcane Shoulderguards", zh = "魔能机甲的奥术护肩"},
    ["246987"] = {en = "Felreaver's Arcane Helm", zh = "魔能机甲的奥术之盔"},
    ["246988"] = {en = "Felreaver's Arcane Treads", zh = "魔能机甲的奥术之履"},
    ["246989"] = {en = "Ensemble: Felreaver's Arcane Attire", zh = "套装：魔能机甲的奥术装束"},
    ["246990"] = {en = "Felreaver's Azure Staff", zh = "魔能机甲的碧蓝法杖"},
    ["246991"] = {en = "Felreaver's Legion Staff", zh = "魔能机甲的军团法杖"},
    ["246992"] = {en = "Infernal's Profane Staff", zh = "地狱火的亵渎之杖"},
    ["246994"] = {en = "Felreaver's Hellfire Staff", zh = "魔能机甲的地狱火法杖"},
    ["246996"] = {en = "Felreaver's Azure Wand", zh = "魔能机甲的碧蓝魔杖"},
    ["246997"] = {en = "Felreaver's Legion Wand", zh = "魔能机甲的军团魔杖"},
    ["246998"] = {en = "Felreaver's Hellfire Wand", zh = "魔能机甲的地狱火魔杖"},
    ["246999"] = {en = "Infernal's Profane Touch", zh = "地狱火的亵渎之触"},
    ["247685"] = {en = "Slightly Used Containment Device", zh = "二手禁锢装置"},
    ["247686"] = {en = "Crystallized Nightshade", zh = "晶化夜影花"},
    ["247687"] = {en = "Overly-Preserved K'areshi Preserves", zh = "储存过久的卡雷什贮藏"},
    ["247688"] = {en = "K'arroc Feather Quill", zh = "卡雷鹏羽毛笔"},
    ["247689"] = {en = "K'areshi Copper Ingot", zh = "卡雷什铜锭"},
    ["247690"] = {en = "Void-Tainted Lotus", zh = "虚空侵染的莲花"},
    ["247691"] = {en = "Slateback Hide", zh = "岩背皮毛"},
    ["247692"] = {en = "K'areshi Grain Fluff", zh = "卡雷什谷物软块"},
    ["247693"] = {en = "Fermented Warpstalker Niblets", zh = "发酵的迁跃兽肉粒"},
    ["247694"] = {en = "Snifted Void Essence", zh = "吸入式虚空精华"},
    ["247695"] = {en = "Sparkling Mana Supplement", zh = "闪光法力滋补品"},
    ["247696"] = {en = "Pungent Smelling Salts", zh = "浓郁气息精盐"},
    ["247698"] = {en = "Deep-Fired Devourer Legs", zh = "油炸吞噬者腿肉"},
    ["247699"] = {en = "Coagulated \"Milk\" Protein", zh = "凝结“乳”蛋白"},
    ["247700"] = {en = "Genuine K'areshi Honey", zh = "正宗卡雷什蜂蜜"},
    ["247703"] = {en = "Reshii Hood", zh = "雷什兜帽"},
    ["247704"] = {en = "Reshii Mantle", zh = "雷什披肩"},
    ["247705"] = {en = "The Horseman's Chilling Blade", zh = "骑士的悚然利剑"},
    ["247706"] = {en = "The Horseman's Ghoulish Blade", zh = "骑士的恐怖利剑"},
    ["247707"] = {en = "The Horseman's Burning Blade", zh = "骑士的炽燃利剑"},
    ["247708"] = {en = "The Horseman's Hallowed Blade", zh = "骑士的圣洁利剑"},
    ["247709"] = {en = "The Horseman's Chilling Great Blade", zh = "骑士的悚然大剑"},
    ["247710"] = {en = "The Horseman's Ghoulish Great Blade", zh = "骑士的恐怖大剑"},
    ["247711"] = {en = "The Horseman's Burning Great Blade", zh = "骑士的炽燃大剑"},
    ["247712"] = {en = "The Horseman's Hallowed Great Blade", zh = "骑士的圣洁大剑"},
    ["247714"] = {en = "The Horseman's Chilling Bulwark", zh = "骑士的悚然壁垒"},
    ["247715"] = {en = "The Horseman's Ghoulish Bulwark", zh = "骑士的恐怖壁垒"},
    ["247716"] = {en = "The Horseman's Burning Bulwark", zh = "骑士的炽燃壁垒"},
    ["247717"] = {en = "The Horseman's Hallowed Bulwark", zh = "骑士的圣洁壁垒"},
    ["247720"] = {en = "The Headless Horseman's Chilling Charger", zh = "无头骑士的悚然战马"},
    ["247721"] = {en = "The Headless Horseman's Ghoulish Charger", zh = "无头骑士的恐怖战马"},
    ["247722"] = {en = "The Headless Horseman's Burning Charger", zh = "无头骑士的炽燃战马"},
    ["247723"] = {en = "The Headless Horseman's Hallowed Charger", zh = "无头骑士的圣洁战马"},
    ["247791"] = {en = "Adorned Northeron Gryphon", zh = "华丽的诺瑟隆狮鹫"},
    ["247792"] = {en = "High Shaman's Aerie Gryphon", zh = "高阶萨满祭司的飞天狮鹫"},
    ["247793"] = {en = "Cinder-Plumed Highland Gryphon", zh = "烬羽高地狮鹫"},
    ["247794"] = {en = "Emberwing Sky Guide", zh = "烬翼巡天向导"},
    ["247795"] = {en = "Ornery Breezestrider", zh = "暴躁风蹄羊"},
    ["247820"] = {en = "Cache of K'areshi Treasures", zh = "一箱卡雷什宝藏"},
    ["247821"] = {en = "Cache of K'areshi Treasures", zh = "一箱卡雷什宝藏"},
    ["247822"] = {en = "Scarlet Void Flyer", zh = "赤红虚空飞镰虫"},
    ["247835"] = {en = "Memory of Illidan", zh = "伊利丹的回忆"},
    ["247864"] = {en = "Memory of Arthas", zh = "阿尔萨斯的回忆"},
    ["247865"] = {en = "Memory of Garrosh", zh = "加尔鲁什的回忆"},
    ["247866"] = {en = "Memory of Guldan", zh = "古尔丹的回忆"},
    ["247867"] = {en = "Memory of Suramar", zh = "苏拉玛的回忆"},
    ["247869"] = {en = "Memory of Putricide", zh = "普崔塞德的回忆"},
    ["247870"] = {en = "Memory of Saurfang", zh = "萨鲁法尔的回忆"},
    ["247871"] = {en = "Memory of Sylvanas", zh = "希尔瓦娜斯的回忆"},
    ["247872"] = {en = "Memory of Theotar", zh = "西塔尔的回忆"},
    ["247873"] = {en = "Memory of Thrall", zh = "萨尔的回忆"},
    ["247882"] = {en = "Phase Regulator", zh = "相位调节器"},
    ["247897"] = {en = "The Horseman's Chilling Helm", zh = "骑士的悚然头盔"},
    ["247898"] = {en = "The Horseman's Chilling Mantle", zh = "骑士的悚然披肩"},
    ["247899"] = {en = "The Horseman's Chilling Breastplate", zh = "骑士的悚然胸铠"},
    ["247900"] = {en = "The Horseman's Chilling Cinch", zh = "骑士的悚然束带"},
    ["247901"] = {en = "The Horseman's Chilling Greaves", zh = "骑士的悚然护胫"},
    ["247903"] = {en = "The Horseman's Chilling Treads", zh = "骑士的悚然踏靴"},
    ["247904"] = {en = "The Horseman's Chilling Grips", zh = "骑士的悚然护手"},
    ["247905"] = {en = "The Horseman's Chilling Cloak", zh = "骑士的悚然披风"},
    ["247906"] = {en = "Ensemble: The Horseman's Chilling Collection", zh = "套装：骑士的悚然收藏"},
    ["247926"] = {en = "Muted Mana-Stone", zh = "静默法力之石"},
    ["247927"] = {en = "Humming Mana-Stone", zh = "嗡鸣法力之石"},
    ["247964"] = {en = "The Horseman's Ghoulish Helm", zh = "骑士的恐怖头盔"},
    ["247965"] = {en = "The Horseman's Ghoulish Mantle", zh = "骑士的恐怖披肩"},
    ["247966"] = {en = "The Horseman's Ghoulish Breastplate", zh = "骑士的恐怖胸铠"},
    ["247967"] = {en = "The Horseman's Ghoulish Cinch", zh = "骑士的恐怖束带"},
    ["247968"] = {en = "The Horseman's Ghoulish Greaves", zh = "骑士的恐怖护胫"},
    ["247969"] = {en = "The Horseman's Ghoulish Treads", zh = "骑士的恐怖踏靴"},
    ["247971"] = {en = "The Horseman's Ghoulish Grips", zh = "骑士的恐怖护手"},
    ["247972"] = {en = "The Horseman's Ghoulish Cloak", zh = "骑士的恐怖披风"},
    ["247973"] = {en = "Ensemble: The Horseman's Ghoulish Collection", zh = "套装：骑士的恐怖收藏"},
    ["247974"] = {en = "The Horseman's Burning Helm", zh = "骑士的炽燃头盔"},
    ["247975"] = {en = "The Horseman's Burning Mantle", zh = "骑士的炽燃披肩"},
    ["247976"] = {en = "The Horseman's Burning Breastplate", zh = "骑士的炽燃胸铠"},
    ["247977"] = {en = "The Horseman's Burning Cinch", zh = "骑士的炽燃束带"},
    ["247978"] = {en = "The Horseman's Burning Greaves", zh = "骑士的炽燃护胫"},
    ["247979"] = {en = "The Horseman's Burning Treads", zh = "骑士的炽燃踏靴"},
    ["247980"] = {en = "The Horseman's Burning Grips", zh = "骑士的炽燃护手"},
    ["247981"] = {en = "The Horseman's Burning Cloak", zh = "骑士的炽燃披风"},
    ["247982"] = {en = "Ensemble: The Horseman's Burning Collection", zh = "套装：骑士的炽燃收藏"},
    ["247983"] = {en = "The Horseman's Hallowed Helm", zh = "骑士的圣洁头盔"},
    ["247984"] = {en = "The Horseman's Hallowed Mantle", zh = "骑士的圣洁披肩"},
    ["247985"] = {en = "The Horseman's Hallowed Breastplate", zh = "骑士的圣洁胸铠"},
    ["247986"] = {en = "The Horseman's Hallowed Cinch", zh = "骑士的圣洁束带"},
    ["247987"] = {en = "The Horseman's Hallowed Greaves", zh = "骑士的圣洁护胫"},
    ["247988"] = {en = "The Horseman's Hallowed Treads", zh = "骑士的圣洁踏靴"},
    ["247989"] = {en = "The Horseman's Hallowed Grips", zh = "骑士的圣洁护手"},
    ["247990"] = {en = "The Horseman's Hallowed Cloak", zh = "骑士的圣洁披风"},
    ["247991"] = {en = "Ensemble: The Horseman's Hallowed Collection", zh = "套装：骑士的圣洁收藏"},
    ["248017"] = {en = "Shrieking Quartz", zh = "尖啸石英"},
    ["248126"] = {en = "Delver's Starter Kit", zh = "地下堡行者新手包"},
    ["248127"] = {en = "Delver's Cosmetic Surprise Bag", zh = "地下堡行者的装饰品福袋"},
    ["248129"] = {en = "Brann's Repossessed Gear", zh = "布莱恩回收的装备"},
    ["248142"] = {en = "Delver's Bounty", zh = "地下堡行者的奖赏"},
    ["248199"] = {en = "The Brothers' Final Gift", zh = "兄弟最后的礼物"},
    ["248200"] = {en = "The Brothers' Not-So-Final Present", zh = "兄弟尚未确定的礼物"},
    ["248242"] = {en = "Algari Token of Merit", zh = "阿加功绩奖币"},
    ["248248"] = {en = "Azure Void Flyer", zh = "碧蓝虚空飞镰虫"},
    ["248249"] = {en = "Lightstrider Raiment", zh = "踏光行者的盛装"},
    ["248291"] = {en = "Bronzebeard's Ceremonial Crown", zh = "铜须的仪式冠冕"},
    ["248292"] = {en = "Bronzebeard's Ceremonial Mantle", zh = "铜须的仪式披肩"},
    ["248293"] = {en = "Bronzebeard's Ceremonial Chestplate", zh = "铜须的仪式胸铠"},
    ["248294"] = {en = "Bronzebeard's Ceremonial Belt", zh = "铜须的仪式腰带"},
    ["248295"] = {en = "Bronzebeard's Ceremonial Boots", zh = "铜须的仪式之靴"},
    ["248296"] = {en = "Bronzebeard's Ceremonial Legguards", zh = "铜须的仪式腿甲"},
    ["248297"] = {en = "Bronzebeard's Ceremonial Gauntlets", zh = "铜须的仪式手甲"},
    ["248298"] = {en = "Bronzebeard's Ceremonial Cloak", zh = "铜须的仪式披风"},
    ["248299"] = {en = "Ensemble: Bronzebeard's Ceremonial Collection", zh = "套装：铜须的仪式收藏"},
    ["248301"] = {en = "The Speaker's Ceremonial Crown", zh = "代言人的仪式冠冕"},
    ["248302"] = {en = "The Speaker's Ceremonial Mantle", zh = "代言人的仪式披肩"},
    ["248303"] = {en = "The Speaker's Ceremonial Chestplate", zh = "代言人的仪式胸铠"},
    ["248304"] = {en = "The Speaker's Ceremonial Belt", zh = "代言人的仪式腰带"},
    ["248305"] = {en = "The Speaker's Ceremonial Boots", zh = "代言人的仪式之靴"},
    ["248306"] = {en = "The Speaker's Ceremonial Legguards", zh = "代言人的仪式腿甲"},
    ["248307"] = {en = "The Speaker's Ceremonial Gauntlets", zh = "代言人的仪式手甲"},
    ["248308"] = {en = "The Speaker's Ceremonial Cloak", zh = "代言人的仪式披风"},
    ["248309"] = {en = "Ensemble: The Speaker's Ceremonial Collection", zh = "套装：代言人的仪式收藏"},
    ["248310"] = {en = "Wildhammer's Ceremonial Crown", zh = "蛮锤的仪式冠冕"},
    ["248311"] = {en = "Wildhammer's Ceremonial Mantle", zh = "蛮锤的仪式披肩"},
    ["248312"] = {en = "Wildhammer's Ceremonial Chestplate", zh = "蛮锤的仪式胸铠"},
    ["248313"] = {en = "Wildhammer's Ceremonial Belt", zh = "蛮锤的仪式腰带"},
    ["248314"] = {en = "Wildhammer's Ceremonial Boots", zh = "蛮锤的仪式之靴"},
    ["248315"] = {en = "Wildhammer's Ceremonial Legguards", zh = "蛮锤的仪式腿甲"},
    ["248316"] = {en = "Wildhammer's Ceremonial Gauntlets", zh = "蛮锤的仪式手甲"},
    ["248317"] = {en = "Wildhammer's Ceremonial Cloak", zh = "蛮锤的仪式披风"},
    ["248318"] = {en = "Ensemble: Wildhammer's Ceremonial Collection", zh = "套装：蛮锤的仪式收藏"},
    ["248319"] = {en = "Dark Iron's Ceremonial Crown", zh = "黑铁的仪式冠冕"},
    ["248320"] = {en = "Dark Iron's Draping Mantle", zh = "黑铁的覆合披肩"},
    ["248321"] = {en = "Dark Iron's Ceremonial Chestplate", zh = "黑铁的仪式胸铠"},
    ["248322"] = {en = "Dark Iron's Ceremonial Belt", zh = "黑铁的仪式腰带"},
    ["248323"] = {en = "Dark Iron's Ceremonial Boots", zh = "黑铁的仪式之靴"},
    ["248324"] = {en = "Dark Iron's Ceremonial Legguards", zh = "黑铁的仪式腿甲"},
    ["248325"] = {en = "Dark Iron's Ceremonial Gauntlets", zh = "黑铁的仪式手甲"},
    ["248326"] = {en = "Dark Iron's Ceremonial Cloak", zh = "黑铁的仪式披风"},
    ["248327"] = {en = "Ensemble: Dark Iron's Ceremonial Collection", zh = "套装：黑铁的仪式收藏"},
    ["248331"] = {en = "Umbral Essentia", zh = "晦幽精粹"},
    ["248340"] = {en = "Astral Gladiator's Focus", zh = "星界角斗士的法器"},
    ["248341"] = {en = "Astral Gladiator's Mace", zh = "星界角斗士之锤"},
    ["248343"] = {en = "Astral Gladiator's Dagger", zh = "星界角斗士的匕首"},
    ["248345"] = {en = "Astral Gladiator's Warglaive", zh = "星界角斗士的战刃"},
    ["248346"] = {en = "Astral Gladiator's Spear", zh = "星界角斗士的锐矛"},
    ["248347"] = {en = "Astral Gladiator's Staff", zh = "星界角斗士的法杖"},
    ["248348"] = {en = "Astral Gladiator's Greatsword", zh = "星界角斗士的巨剑"},
    ["248349"] = {en = "Astral Gladiator's Battlestaff", zh = "星界角斗士的战斗法杖"},
    ["248350"] = {en = "Astral Gladiator's Crossbow", zh = "星界角斗士之弩"},
    ["248351"] = {en = "Astral Gladiator's Scepter", zh = "星界角斗士的节杖"},
    ["248352"] = {en = "Astral Gladiator's Focus", zh = "星界角斗士的法器"},
    ["248353"] = {en = "Astral Gladiator's Shield", zh = "星界角斗士的盾牌"},
    ["248355"] = {en = "Astral Gladiator's Claws", zh = "星界角斗士的刃爪"},
    ["248356"] = {en = "Astral Gladiator's Bow", zh = "星界角斗士之弓"},
    ["248358"] = {en = "Astral Gladiator's Pulverizer", zh = "星界角斗士的碎击之锤"},
    ["248359"] = {en = "Astral Gladiator's Sword", zh = "星界角斗士之剑"},
    ["248364"] = {en = "Astral Gladiator's Axe", zh = "星界角斗士之斧"},
    ["248365"] = {en = "Astral Gladiator's Cinquedea", zh = "星界角斗士的五指剑"},
    ["248366"] = {en = "Astral Gladiator's Mace", zh = "星界角斗士之锤"},
    ["248367"] = {en = "Astral Gladiator's Censer", zh = "星界角斗士的香炉"},
    ["248368"] = {en = "Voidstrider's Cloak", zh = "踏虚行者的披风"},
    ["248369"] = {en = "Voidstrider's Gloves", zh = "踏虚行者的手套"},
    ["248370"] = {en = "Voidstrider's Legguards", zh = "踏虚行者的腿甲"},
    ["248371"] = {en = "Voidstrider's Boots", zh = "踏虚行者的长靴"},
    ["248372"] = {en = "Voidstrider's Belt", zh = "踏虚行者的腰带"},
    ["248373"] = {en = "Voidstrider's Chestplate", zh = "踏虚行者的胸铠"},
    ["248374"] = {en = "Voidstrider's Robe", zh = "踏虚行者的长袍"},
    ["248375"] = {en = "Voidstrider's Mantle", zh = "踏虚行者的披肩"},
    ["248376"] = {en = "Voidstrider's Crown", zh = "踏虚行者的头冠"},
    ["248377"] = {en = "Voidstrider's Wristguard", zh = "踏虚行者的腕甲"},
    ["248378"] = {en = "Lightstrider's Cloak", zh = "踏光行者的披风"},
    ["248379"] = {en = "Lightstrider's Gloves", zh = "踏光行者的手套"},
    ["248380"] = {en = "Lightstrider's Legguards", zh = "踏光行者的腿甲"},
    ["248381"] = {en = "Lightstrider's Boots", zh = "踏光行者的长靴"},
    ["248382"] = {en = "Lightstrider's Belt", zh = "踏光行者的腰带"},
    ["248383"] = {en = "Lightstrider's Chestplate", zh = "踏光行者的胸铠"},
    ["248384"] = {en = "Lightstrider's Robe", zh = "踏光行者的长袍"},
    ["248385"] = {en = "Lightstrider's Mantle", zh = "踏光行者的披肩"},
    ["248386"] = {en = "Lightstrider's Crown", zh = "踏光行者的头冠"},
    ["248387"] = {en = "Lightstrider's Wristguard", zh = "踏光行者的腕甲"},
    ["248394"] = {en = "Dark Iron's Crystal Mantle", zh = "黑铁的典礼披肩"},
    ["248395"] = {en = "Wildhammer's Ritualistic Mantle", zh = "蛮锤的典礼披肩"},
    ["248396"] = {en = "The Speaker's Ritualistic Mantle", zh = "代言人的典礼披肩"},
    ["248397"] = {en = "Bronzebeard's Ritualistic Mantle", zh = "铜须的典礼披肩"},
    ["248410"] = {en = "Technomancer's Gift", zh = "科技巫师的馈赠"},
    ["248550"] = {en = "Recipe: Umbral Essentia", zh = "配方：晦幽精粹"},
    ["248585"] = {en = "Umbral Essentia", zh = "晦幽精粹"},
    ["248586"] = {en = "Umbral Essentia", zh = "晦幽精粹"},
    ["248755"] = {en = "Star-in-a-jar", zh = "罐装星辰"},
    ["248761"] = {en = "Brewfest Barrel Bomber", zh = "美酒节酒桶轰炸机"},
    ["248764"] = {en = "Artisanal Blink Trap", zh = "精工闪现陷阱"},
    ["248780"] = {en = "Consortium Brute's Cape", zh = "星界财团蛮兵的披风"},
    ["248781"] = {en = "Consortium Skirmisher's Cloak", zh = "星界财团散兵的斗篷"},
    ["248782"] = {en = "Consortium Scout's Serape", zh = "星界财团斥候的披肩"},
    ["248783"] = {en = "Consortium Magi's Shawl", zh = "星界财团法师的披巾"},
    ["248784"] = {en = "Ensemble: Void-Scarred Captain's Plate", zh = "套装：虚痕队长的板甲"},
    ["248785"] = {en = "Ensemble: Void-Scarred Striker's Battlegear", zh = "套装：虚痕强袭者的战装"},
    ["248786"] = {en = "Ensemble: Void-Scarred Blade's Attire", zh = "套装：虚痕剑士的着装"},
    ["248787"] = {en = "Ensemble: Void-Scarred Seer's Wrappings", zh = "套装：虚痕先知的裹布"},
    ["248788"] = {en = "Ensemble: Bundle of Ethereal Cloaks", zh = "套装：虚灵披风包裹"},
    ["248790"] = {en = "Wastelander Scout's Serape", zh = "废土遗民斥候的披肩"},
    ["248791"] = {en = "Wastelander Skirmisher's Cloak", zh = "废土遗民散兵的斗篷"},
    ["248792"] = {en = "Wastelander Magi's Shawl", zh = "废土遗民法师的披巾"},
    ["248793"] = {en = "Wastelander Brute's Cape", zh = "废土遗民蛮兵的披风"},
    ["248916"] = {en = "Untethered Seer's Capelet", zh = "无拘先知披肩"},
    ["248917"] = {en = "Untethered Blade's Mantle", zh = "无拘剑士披风"},
    ["248918"] = {en = "Untethered Striker's Shroud", zh = "无拘强袭者护袍"},
    ["248919"] = {en = "Untethered Captain's Capote", zh = "无拘队长斗篷"},
    ["248954"] = {en = "Nether-Warped Seedling", zh = "虚空扭曲之种"},
    ["248969"] = {en = "Ensemble: Hollow Sentinel's Wingdrapes", zh = "套装：空洞哨兵的翼帘"},
    ["248970"] = {en = "Nexus-Princess Ky'veza", zh = "节点女亲王凯威扎"},
    ["248971"] = {en = "Ensemble: Vicious Charhound's Felcovers", zh = "套装：灼焦恶犬的狂猎邪袍"},
    ["248972"] = {en = "Ensemble: Plumes of the Mother Eagle", zh = "套装：鹰之母的飞羽"},
    ["248973"] = {en = "Ensemble: Spellweaver's Immaculate Runecloaks", zh = "套装：织法者的无暇符文披风"},
    ["248974"] = {en = "Voidstrider Raiment", zh = "踏虚行者的盛装"},
    ["248976"] = {en = "Ensemble: Midnight Herald's Shrouds", zh = "套装：午夜使者的遮蔽"},
    ["248977"] = {en = "Ensemble: Augur's Ephemeral Brilliance", zh = "套装：预言师的须臾辉光"},
    ["248978"] = {en = "Ensemble: Breeze of Fallen Storms", zh = "套装：陨落风暴的轻拂"},
    ["248979"] = {en = "Ensemble: Gilded Cloaks of the Lucent Battalion", zh = "套装：明光军旅的鎏金披风"},
    ["248980"] = {en = "Ensemble: Memories of a Dying Star", zh = "套装：垂死星辰的追思"},
    ["248981"] = {en = "Ensemble: Capes of the Sudden Eclipse", zh = "套装：瞬时蚀变的披风"},
    ["248982"] = {en = "Ensemble: Shawls of Channeled Fury", zh = "套装：导能狂怒的披巾"},
    ["248983"] = {en = "Ensemble: Inquisitor's All-Seeing Madness", zh = "套装：审判官的全视疯狂"},
    ["248984"] = {en = "Ensemble: Living Weapon's Capes", zh = "套装：刀身剑骨披风"},
    ["248995"] = {en = "Ensemble: Untethered Seer's Vestiture", zh = "套装：无拘先知的衣衫"},
    ["248996"] = {en = "Ensemble: Untethered Blade's Garb", zh = "套装：无拘剑士的衣装"},
    ["248997"] = {en = "Ensemble: Untethered Striker's Gear", zh = "套装：无拘强袭者的戎装"},
    ["248998"] = {en = "Ensemble: Untethered Captain's Full-Plate", zh = "套装：无拘队长全身板甲"},
    ["249028"] = {en = "Perfectly Preserved Kaja'Classic Original Taste", zh = "贮藏完好的卡亚可乐经典原味"},
    ["249029"] = {en = "Ultimate Orange O-pocalypse", zh = "终极香橙启示录"},
    ["249030"] = {en = "Omega Oyster Outbreak", zh = "究极牡蛎爆发"},
    ["249031"] = {en = "Supreme Mangoro Madness", zh = "至尊曼古鲁之狂"},
    ["249032"] = {en = "Dulux Bluesberry Blast", zh = "尊享蓝莓轰击"},
    ["249145"] = {en = "Manaforge Raider's Gamma Shockmace", zh = "法力熔炉奇兵的伽马震荡锤"},
    ["249146"] = {en = "Manaforge Raider's Gamma Plexhammer", zh = "法力熔炉奇兵的伽马集能锤"},
    ["249147"] = {en = "Manaforge Raider's Gamma Beamglaive", zh = "法力熔炉奇兵的伽马光束长刀"},
    ["249148"] = {en = "Manaforge Raider's Gamma Lightshiv", zh = "法力熔炉奇兵的伽马光刀"},
    ["249149"] = {en = "Manaforge Raider's Gamma Recurve", zh = "法力熔炉奇兵的伽马反曲弓"},
    ["249150"] = {en = "Manaforge Raider's Gamma Warpblade", zh = "法力熔炉奇兵的伽马曲刃"},
    ["249151"] = {en = "Manaforge Raider's Gamma Spire", zh = "法力熔炉奇兵的伽马巨杖"},
    ["249152"] = {en = "Manaforge Raider's Gamma Ward", zh = "法力熔炉奇兵的伽马结界"},
    ["249153"] = {en = "Manaforge Raider's Gamma Staff", zh = "法力熔炉奇兵的伽马法杖"},
    ["249154"] = {en = "Manaforge Raider's Gamma Greatsword", zh = "法力熔炉奇兵的伽马大剑"},
    ["249155"] = {en = "Manaforge Raider's Gamma Reactor", zh = "法力熔炉奇兵的伽马反应堆"},
    ["249156"] = {en = "Manaforge Raider's Gamma Phaseblade", zh = "法力熔炉奇兵的伽马相位之剑"},
    ["249157"] = {en = "Manaforge Raider's Gamma Shard", zh = "法力熔炉奇兵的伽马碎刃"},
    ["249158"] = {en = "Manaforge Raider's Gamma Caster", zh = "法力熔炉奇兵的伽马抛射弩"},
    ["249159"] = {en = "Manaforge Raider's Gamma Baton", zh = "法力熔炉奇兵的伽马指挥棒"},
    ["249160"] = {en = "Manaforge Raider's Gamma Hatchet", zh = "法力熔炉奇兵的伽马手斧"},
    ["249161"] = {en = "Manaforge Raider's Gamma Blade", zh = "法力熔炉奇兵的伽马利刃"},
    ["249162"] = {en = "Manaforge Raider's Tyrant Maul", zh = "法力熔炉奇兵的暴君战锤"},
    ["249163"] = {en = "Manaforge Raider's Gamma Starcrusher", zh = "法力熔炉奇兵的伽马碎星者"},
    ["249164"] = {en = "Manaforge Raider's Cosmic Shockmace", zh = "法力熔炉奇兵的宇宙震荡锤"},
    ["249165"] = {en = "Manaforge Raider's Umbral Shockmace", zh = "法力熔炉奇兵的晦幽震荡锤"},
    ["249166"] = {en = "Manaforge Raider's Devouring Shockmace", zh = "法力熔炉奇兵的吞噬震荡锤"},
    ["249167"] = {en = "Manaforge Raider's Cosmic Plexhammer", zh = "法力熔炉奇兵的宇宙集能锤"},
    ["249168"] = {en = "Manaforge Raider's Umbral Plexhammer", zh = "法力熔炉奇兵的晦幽集能锤"},
    ["249169"] = {en = "Manaforge Raider's Devouring Plexhammer", zh = "法力熔炉奇兵的吞噬集能锤"},
    ["249170"] = {en = "Manaforge Raider's Cosmic Beamglaive", zh = "法力熔炉奇兵的宇宙光束长刀"},
    ["249171"] = {en = "Manaforge Raider's Umbral Beamglaive", zh = "法力熔炉奇兵的晦幽光束长刀"},
    ["249172"] = {en = "Manaforge Raider's Devouring Beamglaive", zh = "法力熔炉奇兵的吞噬光束长刀"},
    ["249173"] = {en = "Manaforge Raider's Cosmic Lightshiv", zh = "法力熔炉奇兵的宇宙光刀"},
    ["249174"] = {en = "Manaforge Raider's Umbral Lightshiv", zh = "法力熔炉奇兵的晦幽光刀"},
    ["249175"] = {en = "Manaforge Raider's Devouring Lightshiv", zh = "法力熔炉奇兵的吞噬光刀"},
    ["249176"] = {en = "Manaforge Raider's Cosmic Recurve", zh = "法力熔炉奇兵的宇宙反曲弓"},
    ["249177"] = {en = "Manaforge Raider's Umbral Recurve", zh = "法力熔炉奇兵的晦幽反曲弓"},
    ["249178"] = {en = "Manaforge Raider's Devouring Recurve", zh = "法力熔炉奇兵的吞噬反曲弓"},
    ["249179"] = {en = "Manaforge Raider's Cosmic Warpblade", zh = "法力熔炉奇兵的宇宙曲刃"},
    ["249180"] = {en = "Manaforge Raider's Umbral Warpblade", zh = "法力熔炉奇兵的晦幽曲刃"},
    ["249181"] = {en = "Manaforge Raider's Devouring Warpblade", zh = "法力熔炉奇兵的吞噬曲刃"},
    ["249182"] = {en = "Manaforge Raider's Cosmic Spire", zh = "法力熔炉奇兵的宇宙巨杖"},
    ["249183"] = {en = "Manaforge Raider's Umbral Spire", zh = "法力熔炉奇兵的晦幽巨杖"},
    ["249184"] = {en = "Manaforge Raider's Devouring Spire", zh = "法力熔炉奇兵的吞噬巨杖"},
    ["249185"] = {en = "Manaforge Raider's Cosmic Ward", zh = "法力熔炉奇兵的宇宙结界"},
    ["249186"] = {en = "Manaforge Raider's Umbral Ward", zh = "法力熔炉奇兵的晦幽结界"},
    ["249187"] = {en = "Manaforge Raider's Devouring Ward", zh = "法力熔炉奇兵的吞噬结界"},
    ["249188"] = {en = "Manaforge Raider's Cosmic Staff", zh = "法力熔炉奇兵的宇宙法杖"},
    ["249189"] = {en = "Manaforge Raider's Umbral Staff", zh = "法力熔炉奇兵的晦幽法杖"},
    ["249190"] = {en = "Manaforge Raider's Devouring Staff", zh = "法力熔炉奇兵的吞噬法杖"},
    ["249191"] = {en = "Manaforge Raider's Cosmic Greatsword", zh = "法力熔炉奇兵的宇宙大剑"},
    ["249192"] = {en = "Manaforge Raider's Umbral Greatsword", zh = "法力熔炉奇兵的晦幽大剑"},
    ["249193"] = {en = "Manaforge Raider's Devouring Greatsword", zh = "法力熔炉奇兵的吞噬大剑"},
    ["249194"] = {en = "Manaforge Raider's Cosmic Reactor", zh = "法力熔炉奇兵的宇宙反应堆"},
    ["249195"] = {en = "Manaforge Raider's Umbral Reactor", zh = "法力熔炉奇兵的晦幽反应堆"},
    ["249196"] = {en = "Manaforge Raider's Devouring Reactor", zh = "法力熔炉奇兵的吞噬反应堆"},
    ["249197"] = {en = "Manaforge Raider's Cosmic Phaseblade", zh = "法力熔炉奇兵的宇宙相位之剑"},
    ["249198"] = {en = "Manaforge Raider's Umbral Phaseblade", zh = "法力熔炉奇兵的晦幽相位之剑"},
    ["249199"] = {en = "Manaforge Raider's Devouring Phaseblade", zh = "法力熔炉奇兵的吞噬相位之剑"},
    ["249200"] = {en = "Manaforge Raider's Cosmic Shard", zh = "法力熔炉奇兵的宇宙碎刃"},
    ["249201"] = {en = "Manaforge Raider's Umbral Shard", zh = "法力熔炉奇兵的晦幽碎刃"},
    ["249202"] = {en = "Manaforge Raider's Devouring Shard", zh = "法力熔炉奇兵的吞噬碎刃"},
    ["249203"] = {en = "Manaforge Raider's Cosmic Caster", zh = "法力熔炉奇兵的宇宙抛射弩"},
    ["249204"] = {en = "Manaforge Raider's Umbral Caster", zh = "法力熔炉奇兵的晦幽抛射弩"},
    ["249205"] = {en = "Manaforge Raider's Devouring Caster", zh = "法力熔炉奇兵的吞噬抛射弩"},
    ["249206"] = {en = "Manaforge Raider's Cosmic Baton", zh = "法力熔炉奇兵的宇宙指挥棒"},
    ["249207"] = {en = "Manaforge Raider's Umbral Baton", zh = "法力熔炉奇兵的晦幽指挥棒"},
    ["249208"] = {en = "Manaforge Raider's Devouring Baton", zh = "法力熔炉奇兵的吞噬指挥棒"},
    ["249209"] = {en = "Manaforge Raider's Cosmic Hatchet", zh = "法力熔炉奇兵的宇宙手斧"},
    ["249210"] = {en = "Manaforge Raider's Umbral Hatchet", zh = "法力熔炉奇兵的晦幽手斧"},
    ["249211"] = {en = "Manaforge Raider's Devouring Hatchet", zh = "法力熔炉奇兵的吞噬手斧"},
    ["249212"] = {en = "Manaforge Raider's Cosmic Blade", zh = "法力熔炉奇兵的宇宙利刃"},
    ["249213"] = {en = "Manaforge Raider's Umbral Blade", zh = "法力熔炉奇兵的晦幽利刃"},
    ["249214"] = {en = "Manaforge Raider's Devouring Blade", zh = "法力熔炉奇兵的吞噬利刃"},
    ["249215"] = {en = "Manaforge Raider's Cosmic Starcrusher", zh = "法力熔炉奇兵的宇宙碎星者"},
    ["249216"] = {en = "Manaforge Raider's Umbral Starcrusher", zh = "法力熔炉奇兵的晦幽碎星者"},
    ["249217"] = {en = "Manaforge Raider's Devouring Starcrusher", zh = "法力熔炉奇兵的吞噬碎星者"},
    ["249218"] = {en = "Manaforged Instrument", zh = "法力铸造器具"},
    ["249235"] = {en = "Bottomless Bag of Entropy", zh = "熵能无底包"},
    ["249417"] = {en = "Flamethrower", zh = "火焰喷射器"},
    ["249560"] = {en = "Skymaster's Silver Mantle", zh = "飞行管理员的白银披肩"},
    ["249561"] = {en = "Skymaster's Silver Cloak", zh = "飞行管理员的白银披风"},
    ["249562"] = {en = "Skymaster's Silver Tabard", zh = "飞行管理员的白银战袍"},
    ["249563"] = {en = "Skymaster's Sapphire Crown", zh = "飞行管理员的蓝玉头冠"},
    ["249564"] = {en = "Skymaster's Sapphire Shoulderguards", zh = "飞行管理员的蓝玉护肩"},
    ["249565"] = {en = "Skymaster's Sapphire Epaulets", zh = "飞行管理员的蓝玉肩饰"},
    ["249699"] = {en = "Shadowguard Translocator", zh = "影卫传送器"},
    ["249700"] = {en = "Deal: Cartel Zo", zh = "协议：佐财团"},
    ["249701"] = {en = "Technique: Deal: Cartel Zo", zh = "工艺图：协议：佐财团"},
    ["249702"] = {en = "Deal: Cartel Ba", zh = "协议：巴财团"},
    ["249703"] = {en = "Technique: Deal: Cartel Ba", zh = "工艺图：协议：巴财团"},
    ["249704"] = {en = "Deal: Cartel Om", zh = "协议：欧财团"},
    ["249705"] = {en = "Technique: Deal: Cartel Om", zh = "工艺图：协议：欧财团"},
    ["249706"] = {en = "Gleeful Glamour - Ethereal", zh = "欢乐幻魅 - 虚灵"},
    ["249707"] = {en = "Gleeful Glamour - Ethereal", zh = "欢乐幻魅 - 虚灵"},
    ["249708"] = {en = "Gleeful Glamour - Ethereal", zh = "欢乐幻魅 - 虚灵"},
    ["249709"] = {en = "Formula: Gleeful Glamour - Ethereal", zh = "公式：欢乐幻魅 - 虚灵"},
    ["249710"] = {en = "Cartel Zo Cypher", zh = "佐财团密文"},
    ["249711"] = {en = "Cartel Ba Cypher", zh = "巴财团密文"},
    ["249712"] = {en = "Cartel Om Cypher", zh = "欧财团密文"},
    ["249713"] = {en = "Cartel Transmorpher", zh = "财团幻变器"},
    ["249857"] = {en = "Brewer's Blue Belt", zh = "酿酒师的蓝色腰带"},
    ["249858"] = {en = "Brewer's Basic Belt", zh = "酿酒师的基础腰带"},
    ["249859"] = {en = "Brewer's Green Belt", zh = "酿酒师的绿色腰带"},
    ["249860"] = {en = "Brewer's Black Belt", zh = "酿酒师的黑色腰带"},
    ["250082"] = {en = "T'uure, Remnant of the Naaru", zh = "图雷，纳鲁的残迹"},
    ["250104"] = {en = "Soulbinder's Nethermantle", zh = "缚魂者的虚空披风"},
    ["250107"] = {en = "Nuts and Bolts", zh = "螺帽和螺栓"},
    ["250240"] = {en = "Phase-Lost Slateback", zh = "迷失相位的岩背兽"},
    ["250269"] = {en = "Phase-Lost Longsword", zh = "迷失相位的长剑"},
    ["250270"] = {en = "Phase-Lost Scimitar", zh = "迷失相位的弯刀"},
    ["250271"] = {en = "Phase-Lost Hammer", zh = "迷失相位的战锤"},
    ["250272"] = {en = "Phase-Lost Cudgel", zh = "迷失相位的轻棍"},
    ["250273"] = {en = "Phase-Lost Carver", zh = "迷失相位的刻斧"},
    ["250274"] = {en = "Phase-Lost Hatchet", zh = "迷失相位的短斧"},
    ["250275"] = {en = "Phase-Lost Zweihander", zh = "迷失相位的双手剑"},
    ["250276"] = {en = "Phase-Lost Greatsword", zh = "迷失相位的巨剑"},
    ["250277"] = {en = "Phase-Lost Maul", zh = "迷失相位的重锤"},
    ["250278"] = {en = "Phase-Lost Great Mace", zh = "迷失相位的巨锤"},
    ["250280"] = {en = "Phase-Lost Chopper", zh = "迷失相位的切斧"},
    ["250281"] = {en = "Phase-Lost Battleaxe", zh = "迷失相位的战斧"},
    ["250282"] = {en = "Phase-Lost Bardiche", zh = "迷失相位的弯刃"},
    ["250283"] = {en = "Phase-Lost Spear", zh = "迷失相位的矛枪"},
    ["250284"] = {en = "Phase-Lost Spire", zh = "迷失相位的塔杖"},
    ["250285"] = {en = "Phase-Lost Shillelagh", zh = "迷失相位的橡木棍"},
    ["250286"] = {en = "Phase-Lost Blunderbuss", zh = "迷失相位的火枪"},
    ["250287"] = {en = "Phase-Lost Longbow", zh = "迷失相位的长弓"},
    ["250288"] = {en = "Phase-Lost Baselard", zh = "迷失相位的短刃"},
    ["250289"] = {en = "Phase-Lost Dirk", zh = "迷失相位的短匕"},
    ["250294"] = {en = "Phase-Lost Katar", zh = "迷失相位的拳刃"},
    ["250295"] = {en = "Phase-Lost Claw", zh = "迷失相位的利爪"},
    ["250296"] = {en = "Phase-Lost Sigil", zh = "迷失相位的魔印"},
    ["250297"] = {en = "Phase-Lost Beacon", zh = "迷失相位的信标"},
    ["250298"] = {en = "Phase-Lost Bulwark", zh = "迷失相位的壁垒"},
    ["250299"] = {en = "Phase-Lost Pavise", zh = "迷失相位的巨盾"},
    ["250300"] = {en = "Phase-Lost Rod", zh = "迷失相位的魔棒"},
    ["250301"] = {en = "Phase-Lost Wand", zh = "迷失相位的魔杖"},
    ["250305"] = {en = "Phase-Lost Detritus", zh = "迷失相位的碎屑"},
    ["250430"] = {en = "Darkened Shoulderguards of the Wastelander Seer", zh = "废土遗民先知的深色护肩"},
    ["250431"] = {en = "Golden Shoulderguards of the Wastelander Seer", zh = "废土遗民先知的金色护肩"},
    ["250432"] = {en = "Violet Shoulderguards of the Wastelander Seer", zh = "废土遗民先知的绛紫护肩"},
    ["250433"] = {en = "Crimson Shoulderguards of the Wastelander Seer", zh = "废土遗民先知的深红护肩"},
    ["250434"] = {en = "Verdant Shoulderguards of the Wastelander Seer", zh = "废土遗民先知的翠绿护肩"},
    ["250435"] = {en = "Loamy Shoulderguards of the Wastelander Seer", zh = "废土遗民先知的褐色护肩"},
    ["250436"] = {en = "Capelet of the Reshii", zh = "雷什的短披"},
    ["250437"] = {en = "Cloak of the Reshii", zh = "雷什的斗篷"},
    ["250438"] = {en = "Serape of the Reshii", zh = "雷什的披肩"},
    ["250439"] = {en = "Stole of the Reshii", zh = "雷什的圣带"},
    ["250441"] = {en = "Ensemble: Shoulderguards of the Wastelander Seer", zh = "套装：废土遗民先知的护肩"},
    ["250442"] = {en = "Ensemble: Ancient Capes of the Reshii", zh = "套装：雷什的远古披风"},
    ["250706"] = {en = "The Horseman's Hallowed Cowl", zh = "骑士的圣洁兜帽"},
    ["250707"] = {en = "The Horseman's Burning Cowl", zh = "骑士的炽燃兜帽"},
    ["250708"] = {en = "The Horseman's Ghoulish Cowl", zh = "骑士的恐怖兜帽"},
    ["250709"] = {en = "The Horseman's Chilling Cowl", zh = "骑士的悚然兜帽"},
    ["250722"] = {en = "Ethereal Stall", zh = "虚灵商摊"},
    ["250763"] = {en = "Theater Troupe's Trove", zh = "剧团财宝"},
    ["250764"] = {en = "Nanny's Surge Dividends", zh = "奶奶的峰时红利"},
    ["250765"] = {en = "Awakened Mechanical Cache", zh = "觉醒的机械之箱"},
    ["250766"] = {en = "Radiant Cache", zh = "光耀之箱"},
    ["250767"] = {en = "The General's War Chest", zh = "将军的战争宝箱"},
    ["250768"] = {en = "The Vizier's Capital", zh = "宰相的资金"},
    ["250769"] = {en = "The Weaver's Gratuity", zh = "纺丝者的酬谢"},
    ["250776"] = {en = "Illusion: Sha Corruption", zh = "幻象：煞能腐蚀"},
    ["250975"] = {en = "Hellcaller Chest", zh = "地狱召唤者宝箱"},
    ["251529"] = {en = "Void-Scarred Striker's Cloak", zh = "虚痕强袭者披风"},
    ["251530"] = {en = "Void-Scarred Captain's Cape", zh = "虚痕队长斗篷"},
    ["251531"] = {en = "Void-Scarred Seer's Shawl", zh = "虚痕先知斗披"},
    ["251532"] = {en = "Void-Scarred Blade's Serape", zh = "虚痕剑士披肩"},
    ["251543"] = {en = "Cracked Keystone", zh = "破裂的钥石"},
    ["251880"] = {en = "Momma's Mega Medallion", zh = "老娘的超级大勋章"},
    ["252009"] = {en = "Bloodstained Memento", zh = "血污纪念品"},
    ["254307"] = {en = "Conqueror's Astral Varnish", zh = "征服者的星界清漆"},
    ["254308"] = {en = "Conqueror's Astral Lacquer", zh = "征服者的星界火漆"},
    ["255676"] = {en = "Phase Diver's Cache", zh = "相位潜者的箱子"},
}
